services:
  navidrome:
    image: navidrome-qo:latest
    build:
      context: .
      dockerfile: Dockerfile.fixed
      args:
        GIT_SHA: ${GIT_SHA:-dev}
        GIT_TAG: ${GIT_TAG:-v0.58.0-QO}
    container_name: navidrome-qo
    restart: unless-stopped
    ports:
      - "4533:4533"
    environment:
      # Basic config
      ND_CONFIGFILE: ""
      ND_LOGLEVEL: info
      ND_SESSIONTIMEOUT: 24h
      ND_BASEURL: ""
      ND_MUSICFOLDER: "/music"
      ND_DATAFOLDER: "/data" 
      # Scanning
      ND_SCANSCHEDULE: "@every 1h"
      ND_AUTOIMPORTPLAYLISTS: "true"

      # Performance
      ND_TRANSCODINGCACHESIZE: "100MB"
      ND_IMAGECACHESIZE: "100MB"

      # UI
      ND_UIWELCOMEMESSAGE: "Qırım Online"
      ND_ENABLESHARING: "true"
      ND_ENABLESELFREGISTRATION: "true"
      ND_DEFAULTTHEME: "QODarkTheme"
      ND_ENABLEDOWNLOADS: "false"

      # OAuth Configuration (optional - uncomment to enable)
      ND_OAUTH_ENABLED: "true"
      ND_OAUTH_AUTOCREATEUSER: "true"
      ND_OAUTH_AUTOCREATEUSERADMIN: "false"

      # Google OAuth
      ND_OAUTH_GOOGLE_ENABLED: "true"
      ND_OAUTH_GOOGLE_CLIENTID: "1070163609265-4kaitbf31t4563am55c7eb0nviviohp1.apps.googleusercontent.com"
      ND_OAUTH_GOOGLE_CLIENTSECRET: "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"

      # Apple OAuth
      # ND_OAUTH_APPLE_ENABLED: "true"
      # ND_OAUTH_APPLE_CLIENTID: "qirim.online.web.signin"
      # ND_OAUTH_APPLE_CLIENTSECRET: "${OAUTH_APPLE_CLIENTSECRET}"

      # Instagram OAuth
      ND_OAUTH_INSTAGRAM_ENABLED: "true"
      ND_OAUTH_INSTAGRAM_CLIENTID: "273279853519362"
      ND_OAUTH_INSTAGRAM_CLIENTSECRET: "9851dc8c30088c3d13994ec211675953"

      # Facebook OAuth
      ND_OAUTH_FACEBOOK_ENABLED: "true"
      ND_OAUTH_FACEBOOK_CLIENTID: "273279853519362"
      ND_OAUTH_FACEBOOK_CLIENTSECRET: "9851dc8c30088c3d13994ec211675953"
    volumes:
      - /opt/navidrome/data:/data
      - /opt/navidrome/music:/music:ro
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:4533/ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    networks:
      - navidrome-net

  # Nginx reverse proxy with SSL
  nginx:
    image: nginx:alpine
    container_name: navidrome-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
      - certbot-data:/var/www/certbot:ro
      - certbot-conf:/etc/letsencrypt:ro
    depends_on:
      - navidrome
    networks:
      - navidrome-net

  # Certbot for SSL certificates
  certbot:
    image: certbot/certbot:latest
    container_name: navidrome-certbot
    volumes:
      - certbot-data:/var/www/certbot
      - certbot-conf:/etc/letsencrypt
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

volumes:
  certbot-data:
    driver: local
  certbot-conf:
    driver: local

networks:
  navidrome-net:
    driver: bridge
